
package publicar.ws.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "BusinessException", targetNamespace = "http://publicar/")
public class BusinessException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BusinessException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BusinessException_Exception(String message, BusinessException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public BusinessException_Exception(String message, BusinessException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.BusinessException
     */
    public BusinessException getFaultInfo() {
        return faultInfo;
    }

}
