
package publicar.ws.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NombreEdicionException", targetNamespace = "http://publicar/")
public class NombreEdicionException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NombreEdicionException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NombreEdicionException_Exception(String message, NombreEdicionException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NombreEdicionException_Exception(String message, NombreEdicionException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.NombreEdicionException
     */
    public NombreEdicionException getFaultInfo() {
        return faultInfo;
    }

}
