
package publicar.ws.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "TipoRegistroDuplicadoException", targetNamespace = "http://publicar/")
public class TipoRegistroDuplicadoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TipoRegistroDuplicadoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TipoRegistroDuplicadoException_Exception(String message, TipoRegistroDuplicadoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public TipoRegistroDuplicadoException_Exception(String message, TipoRegistroDuplicadoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.TipoRegistroDuplicadoException
     */
    public TipoRegistroDuplicadoException getFaultInfo() {
        return faultInfo;
    }

}
