
package publicar.ws.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import net.java.dev.jaxb.array.AnyTypeArray;
import net.java.dev.jaxb.array.StringArray;
import net.java.dev.jaxb.array.StringArrayArray;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebServices", targetNamespace = "http://publicar/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    net.java.dev.jaxb.array.ObjectFactory.class,
    publicar.ws.client.ObjectFactory.class
})
public interface WebServices {


    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarUsuariosRequest", output = "http://publicar/WebServices/listarUsuariosResponse")
    public StringArray listarUsuarios();

    /**
     * 
     * @param nickname
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/consultarUsuarioRequest", output = "http://publicar/WebServices/consultarUsuarioResponse")
    public StringArray consultarUsuario(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname);

    /**
     * 
     * @param nicknameAsistente
     * @param nombreEdicion
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/asistenteEstaRegistradoEnEdicionRequest", output = "http://publicar/WebServices/asistenteEstaRegistradoEnEdicionResponse")
    public boolean asistenteEstaRegistradoEnEdicion(
        @WebParam(name = "nicknameAsistente", partName = "nicknameAsistente")
        String nicknameAsistente,
        @WebParam(name = "nombreEdicion", partName = "nombreEdicion")
        String nombreEdicion);

    /**
     * 
     * @return
     *     returns publicar.OrganizadorDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarOrganizadoresDTORequest", output = "http://publicar/WebServices/listarOrganizadoresDTOResponse")
    public OrganizadorDTOArray listarOrganizadoresDTO();

    /**
     * 
     * @param nicknameAsistente
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/obtenerEdicionesRegistradasDeAsistenteRequest", output = "http://publicar/WebServices/obtenerEdicionesRegistradasDeAsistenteResponse")
    public StringArray obtenerEdicionesRegistradasDeAsistente(
        @WebParam(name = "nicknameAsistente", partName = "nicknameAsistente")
        String nicknameAsistente);

    /**
     * 
     * @param nickname
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarEventosPorOrganizadorRequest", output = "http://publicar/WebServices/listarEventosPorOrganizadorResponse")
    public StringArray listarEventosPorOrganizador(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname);

    /**
     * 
     * @param nicknameSeguido
     * @param nicknameSeguidor
     * @throws BusinessException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/seguirUsuarioRequest", output = "http://publicar/WebServices/seguirUsuarioResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/seguirUsuario/Fault/BusinessException")
    })
    public void seguirUsuario(
        @WebParam(name = "nicknameSeguidor", partName = "nicknameSeguidor")
        String nicknameSeguidor,
        @WebParam(name = "nicknameSeguido", partName = "nicknameSeguido")
        String nicknameSeguido)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param nicknameSeguido
     * @param nicknameSeguidor
     * @throws BusinessException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/dejarDeSeguirUsuarioRequest", output = "http://publicar/WebServices/dejarDeSeguirUsuarioResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/dejarDeSeguirUsuario/Fault/BusinessException")
    })
    public void dejarDeSeguirUsuario(
        @WebParam(name = "nicknameSeguidor", partName = "nicknameSeguidor")
        String nicknameSeguidor,
        @WebParam(name = "nicknameSeguido", partName = "nicknameSeguido")
        String nicknameSeguido)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param nickname
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/obtenerSeguidoresRequest", output = "http://publicar/WebServices/obtenerSeguidoresResponse")
    public StringArray obtenerSeguidores(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname);

    /**
     * 
     * @param nickname
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/obtenerSeguidosRequest", output = "http://publicar/WebServices/obtenerSeguidosResponse")
    public StringArray obtenerSeguidos(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname);

    /**
     * 
     * @param contrasenia
     * @param nicknameOEmail
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/verificarLoginRequest", output = "http://publicar/WebServices/verificarLoginResponse")
    public boolean verificarLogin(
        @WebParam(name = "nicknameOEmail", partName = "nicknameOEmail")
        String nicknameOEmail,
        @WebParam(name = "contrasenia", partName = "contrasenia")
        String contrasenia);

    /**
     * 
     * @param nombre
     * @return
     *     returns publicar.InstitucionDTO
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/buscarInstitucionDTORequest", output = "http://publicar/WebServices/buscarInstitucionDTOResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/buscarInstitucionDTO/Fault/BusinessException")
    })
    public InstitucionDTO buscarInstitucionDTO(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param nombre
     * @throws BusinessException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/altaCategoriaRequest", output = "http://publicar/WebServices/altaCategoriaResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/altaCategoria/Fault/BusinessException")
    })
    public void altaCategoria(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param asistio
     * @param nicknameAsistente
     * @param nombreEdicion
     * @param nombreTipoRegistro
     * @throws CupoLlenoException_Exception
     * @throws RegistroDuplicadoException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/registrarAsistenteConAsistenteRequest", output = "http://publicar/WebServices/registrarAsistenteConAsistenteResponse", fault = {
        @FaultAction(className = CupoLlenoException_Exception.class, value = "http://publicar/WebServices/registrarAsistenteConAsistente/Fault/CupoLlenoException"),
        @FaultAction(className = RegistroDuplicadoException_Exception.class, value = "http://publicar/WebServices/registrarAsistenteConAsistente/Fault/RegistroDuplicadoException")
    })
    public void registrarAsistenteConAsistente(
        @WebParam(name = "nicknameAsistente", partName = "nicknameAsistente")
        String nicknameAsistente,
        @WebParam(name = "nombreTipoRegistro", partName = "nombreTipoRegistro")
        String nombreTipoRegistro,
        @WebParam(name = "nombreEdicion", partName = "nombreEdicion")
        String nombreEdicion,
        @WebParam(name = "asistio", partName = "asistio")
        boolean asistio)
        throws CupoLlenoException_Exception, RegistroDuplicadoException_Exception
    ;

    /**
     * 
     * @return
     *     returns publicar.EdicionDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarTodasLasEdicionesDTORequest", output = "http://publicar/WebServices/listarTodasLasEdicionesDTOResponse")
    public EdicionDTOArray listarTodasLasEdicionesDTO();

    /**
     * 
     * @param nombreEdicion
     * @param nombreTipo
     * @return
     *     returns publicar.TipoRegistroDTO
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/buscarTipoRegistroDTORequest", output = "http://publicar/WebServices/buscarTipoRegistroDTOResponse")
    public TipoRegistroDTO buscarTipoRegistroDTO(
        @WebParam(name = "nombreEdicion", partName = "nombreEdicion")
        String nombreEdicion,
        @WebParam(name = "nombreTipo", partName = "nombreTipo")
        String nombreTipo);

    /**
     * 
     * @param nombreEvento
     * @throws BusinessException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/finalizarEventoRequest", output = "http://publicar/WebServices/finalizarEventoResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/finalizarEvento/Fault/BusinessException")
    })
    public void finalizarEvento(
        @WebParam(name = "nombreEvento", partName = "nombreEvento")
        String nombreEvento)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param nicknameOrganizador
     * @param nombreEdicion
     * @throws BusinessException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/archivarEdicionRequest", output = "http://publicar/WebServices/archivarEdicionResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/archivarEdicion/Fault/BusinessException")
    })
    public void archivarEdicion(
        @WebParam(name = "nombreEdicion", partName = "nombreEdicion")
        String nombreEdicion,
        @WebParam(name = "nicknameOrganizador", partName = "nicknameOrganizador")
        String nicknameOrganizador)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param nicknameAsistente
     * @param nombreEdicion
     * @throws BusinessException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/registrarAsistenciaRequest", output = "http://publicar/WebServices/registrarAsistenciaResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/registrarAsistencia/Fault/BusinessException")
    })
    public void registrarAsistencia(
        @WebParam(name = "nicknameAsistente", partName = "nicknameAsistente")
        String nicknameAsistente,
        @WebParam(name = "nombreEdicion", partName = "nombreEdicion")
        String nombreEdicion)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param nombreEvento
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/registrarVisitaRequest", output = "http://publicar/WebServices/registrarVisitaResponse")
    public void registrarVisita(
        @WebParam(name = "nombreEvento", partName = "nombreEvento")
        String nombreEvento);

    /**
     * 
     * @param nombreEvento
     * @param visitas
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/setVisitasEventoRequest", output = "http://publicar/WebServices/setVisitasEventoResponse")
    public void setVisitasEvento(
        @WebParam(name = "nombreEvento", partName = "nombreEvento")
        String nombreEvento,
        @WebParam(name = "visitas", partName = "visitas")
        int visitas);

    /**
     * 
     * @param query
     * @return
     *     returns net.java.dev.jaxb.array.AnyTypeArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/buscarEventosYEdicionesRequest", output = "http://publicar/WebServices/buscarEventosYEdicionesResponse")
    public AnyTypeArray buscarEventosYEdiciones(
        @WebParam(name = "query", partName = "query")
        String query);

    /**
     * 
     * @param nickname
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/esAsistenteRequest", output = "http://publicar/WebServices/esAsistenteResponse")
    public boolean esAsistente(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname);

    /**
     * 
     * @param categorias
     * @param descripcion
     * @param fechaAlta
     * @param imagen
     * @param nombre
     * @param sigla
     * @throws BusinessException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/altaEventoConFechaAltaRequest", output = "http://publicar/WebServices/altaEventoConFechaAltaResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/altaEventoConFechaAlta/Fault/BusinessException")
    })
    public void altaEventoConFechaAlta(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "sigla", partName = "sigla")
        String sigla,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion,
        @WebParam(name = "categorias", partName = "categorias")
        CategoriaDTOArray categorias,
        @WebParam(name = "imagen", partName = "imagen")
        String imagen,
        @WebParam(name = "fechaAlta", partName = "fechaAlta")
        String fechaAlta)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param ciudad
     * @param estado
     * @param fechaAlta
     * @param fechaFin
     * @param fechaInicio
     * @param imagen
     * @param nombre
     * @param nombreEvento
     * @param nombreOrganizador
     * @param pais
     * @param sigla
     * @param videoUrl
     * @throws NombreEdicionException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/altaEdicionEventoConEstadoRequest", output = "http://publicar/WebServices/altaEdicionEventoConEstadoResponse", fault = {
        @FaultAction(className = NombreEdicionException_Exception.class, value = "http://publicar/WebServices/altaEdicionEventoConEstado/Fault/NombreEdicionException")
    })
    public void altaEdicionEventoConEstado(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "sigla", partName = "sigla")
        String sigla,
        @WebParam(name = "fechaInicio", partName = "fechaInicio")
        String fechaInicio,
        @WebParam(name = "fechaFin", partName = "fechaFin")
        String fechaFin,
        @WebParam(name = "fechaAlta", partName = "fechaAlta")
        String fechaAlta,
        @WebParam(name = "nombreOrganizador", partName = "nombreOrganizador")
        String nombreOrganizador,
        @WebParam(name = "ciudad", partName = "ciudad")
        String ciudad,
        @WebParam(name = "pais", partName = "pais")
        String pais,
        @WebParam(name = "nombreEvento", partName = "nombreEvento")
        String nombreEvento,
        @WebParam(name = "imagen", partName = "imagen")
        String imagen,
        @WebParam(name = "videoUrl", partName = "videoUrl")
        String videoUrl,
        @WebParam(name = "estado", partName = "estado")
        String estado)
        throws NombreEdicionException_Exception
    ;

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarEventosNoFinalizadosRequest", output = "http://publicar/WebServices/listarEventosNoFinalizadosResponse")
    public StringArray listarEventosNoFinalizados();

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarInstitucionesRequest", output = "http://publicar/WebServices/listarInstitucionesResponse")
    public StringArray listarInstituciones();

    /**
     * 
     * @param nickname
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/existeNicknameRequest", output = "http://publicar/WebServices/existeNicknameResponse")
    public boolean existeNickname(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname);

    /**
     * 
     * @param correo
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/existeCorreoRequest", output = "http://publicar/WebServices/existeCorreoResponse")
    public boolean existeCorreo(
        @WebParam(name = "correo", partName = "correo")
        String correo);

    /**
     * 
     * @param apellido
     * @param contrasenia
     * @param correo
     * @param fechaNacimiento
     * @param imagen
     * @param institucion
     * @param nickname
     * @param nombre
     * @throws BusinessException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/altaAsistenteRequest", output = "http://publicar/WebServices/altaAsistenteResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/altaAsistente/Fault/BusinessException")
    })
    public void altaAsistente(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "correo", partName = "correo")
        String correo,
        @WebParam(name = "contrasenia", partName = "contrasenia")
        String contrasenia,
        @WebParam(name = "imagen", partName = "imagen")
        String imagen,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "fechaNacimiento", partName = "fechaNacimiento")
        String fechaNacimiento,
        @WebParam(name = "institucion", partName = "institucion")
        String institucion)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param contrasenia
     * @param correo
     * @param descripcion
     * @param imagen
     * @param nickname
     * @param nombre
     * @param sitioWeb
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/altaOrganizadorRequest", output = "http://publicar/WebServices/altaOrganizadorResponse")
    public void altaOrganizador(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "correo", partName = "correo")
        String correo,
        @WebParam(name = "contrasenia", partName = "contrasenia")
        String contrasenia,
        @WebParam(name = "imagen", partName = "imagen")
        String imagen,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion,
        @WebParam(name = "sitioWeb", partName = "sitioWeb")
        String sitioWeb);

    /**
     * 
     * @param nicknameAsistente
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/obtenerRegistrosDeAsistenteRequest", output = "http://publicar/WebServices/obtenerRegistrosDeAsistenteResponse")
    public StringArray obtenerRegistrosDeAsistente(
        @WebParam(name = "nicknameAsistente", partName = "nicknameAsistente")
        String nicknameAsistente);

    /**
     * 
     * @param nicknameOrganizador
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/obtenerEdicionesOrganizadasPorRequest", output = "http://publicar/WebServices/obtenerEdicionesOrganizadasPorResponse")
    public StringArray obtenerEdicionesOrganizadasPor(
        @WebParam(name = "nicknameOrganizador", partName = "nicknameOrganizador")
        String nicknameOrganizador);

    /**
     * 
     * @return
     *     returns publicar.EventoDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarEventosDTORequest", output = "http://publicar/WebServices/listarEventosDTOResponse")
    public EventoDTOArray listarEventosDTO();

    /**
     * 
     * @param nombreEvento
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarEdicionesDeEventoRequest", output = "http://publicar/WebServices/listarEdicionesDeEventoResponse")
    public StringArray listarEdicionesDeEvento(
        @WebParam(name = "nombreEvento", partName = "nombreEvento")
        String nombreEvento);

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarAsistentesRequest", output = "http://publicar/WebServices/listarAsistentesResponse")
    public StringArray listarAsistentes();

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarOrganizadoresRequest", output = "http://publicar/WebServices/listarOrganizadoresResponse")
    public StringArray listarOrganizadores();

    /**
     * 
     * @param nickname
     * @return
     *     returns publicar.AsistenteDTO
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/buscarAsistenteDTORequest", output = "http://publicar/WebServices/buscarAsistenteDTOResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/buscarAsistenteDTO/Fault/BusinessException")
    })
    public AsistenteDTO buscarAsistenteDTO(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param nickname
     * @return
     *     returns publicar.OrganizadorDTO
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/buscarOrganizadorDTORequest", output = "http://publicar/WebServices/buscarOrganizadorDTOResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/buscarOrganizadorDTO/Fault/BusinessException")
    })
    public OrganizadorDTO buscarOrganizadorDTO(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param nombreEdicion
     * @return
     *     returns publicar.TipoRegistroDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/obtenerTiposDeRegistroDeEdicionDTORequest", output = "http://publicar/WebServices/obtenerTiposDeRegistroDeEdicionDTOResponse")
    public TipoRegistroDTOArray obtenerTiposDeRegistroDeEdicionDTO(
        @WebParam(name = "nombreEdicion", partName = "nombreEdicion")
        String nombreEdicion);

    /**
     * 
     * @param nombreEdicion
     * @return
     *     returns publicar.RegistroDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/obtenerRegistrosDeEdicionDTORequest", output = "http://publicar/WebServices/obtenerRegistrosDeEdicionDTOResponse")
    public RegistroDTOArray obtenerRegistrosDeEdicionDTO(
        @WebParam(name = "nombreEdicion", partName = "nombreEdicion")
        String nombreEdicion);

    /**
     * 
     * @param nombreEdicion
     * @return
     *     returns publicar.PatrocinioDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/obtenerPatrociniosDeEdicionDTORequest", output = "http://publicar/WebServices/obtenerPatrociniosDeEdicionDTOResponse")
    public PatrocinioDTOArray obtenerPatrociniosDeEdicionDTO(
        @WebParam(name = "nombreEdicion", partName = "nombreEdicion")
        String nombreEdicion);

    /**
     * 
     * @param costo
     * @param cupo
     * @param descripcion
     * @param nombre
     * @param nombreEdicion
     * @param nombreEvento
     * @throws TipoRegistroDuplicadoException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/altaTipoRegistroRequest", output = "http://publicar/WebServices/altaTipoRegistroResponse", fault = {
        @FaultAction(className = TipoRegistroDuplicadoException_Exception.class, value = "http://publicar/WebServices/altaTipoRegistro/Fault/TipoRegistroDuplicadoException")
    })
    public void altaTipoRegistro(
        @WebParam(name = "nombreEvento", partName = "nombreEvento")
        String nombreEvento,
        @WebParam(name = "nombreEdicion", partName = "nombreEdicion")
        String nombreEdicion,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion,
        @WebParam(name = "costo", partName = "costo")
        String costo,
        @WebParam(name = "cupo", partName = "cupo")
        int cupo)
        throws TipoRegistroDuplicadoException_Exception
    ;

    /**
     * 
     * @param nombreEvento
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarEdicionesIngresadasRequest", output = "http://publicar/WebServices/listarEdicionesIngresadasResponse")
    public StringArray listarEdicionesIngresadas(
        @WebParam(name = "nombreEvento", partName = "nombreEvento")
        String nombreEvento);

    /**
     * 
     * @param nombreEdicion
     * @param nuevoEstado
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/cambiarEstadoEdicionRequest", output = "http://publicar/WebServices/cambiarEstadoEdicionResponse")
    public void cambiarEstadoEdicion(
        @WebParam(name = "nombreEdicion", partName = "nombreEdicion")
        String nombreEdicion,
        @WebParam(name = "nuevoEstado", partName = "nuevoEstado")
        String nuevoEstado);

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarEventosRequest", output = "http://publicar/WebServices/listarEventosResponse")
    public StringArray listarEventos();

    /**
     * 
     * @param nombre
     * @return
     *     returns publicar.EventoDTO
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/buscarEventoDTORequest", output = "http://publicar/WebServices/buscarEventoDTOResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/buscarEventoDTO/Fault/BusinessException")
    })
    public EventoDTO buscarEventoDTO(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @return
     *     returns publicar.CategoriaDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarCategoriasDTORequest", output = "http://publicar/WebServices/listarCategoriasDTOResponse")
    public CategoriaDTOArray listarCategoriasDTO();

    /**
     * 
     * @param categorias
     * @param descripcion
     * @param imagen
     * @param nombre
     * @param sigla
     * @throws BusinessException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/altaEventoRequest", output = "http://publicar/WebServices/altaEventoResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/altaEvento/Fault/BusinessException")
    })
    public void altaEvento(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "sigla", partName = "sigla")
        String sigla,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion,
        @WebParam(name = "categorias", partName = "categorias")
        CategoriaDTOArray categorias,
        @WebParam(name = "imagen", partName = "imagen")
        String imagen)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param ciudad
     * @param fechaFin
     * @param fechaInicio
     * @param imagen
     * @param nombre
     * @param nombreEvento
     * @param nombreOrganizador
     * @param pais
     * @param sigla
     * @param videoUrl
     * @throws NombreEdicionException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/altaEdicionEventoRequest", output = "http://publicar/WebServices/altaEdicionEventoResponse", fault = {
        @FaultAction(className = NombreEdicionException_Exception.class, value = "http://publicar/WebServices/altaEdicionEvento/Fault/NombreEdicionException")
    })
    public void altaEdicionEvento(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "sigla", partName = "sigla")
        String sigla,
        @WebParam(name = "fechaInicio", partName = "fechaInicio")
        String fechaInicio,
        @WebParam(name = "fechaFin", partName = "fechaFin")
        String fechaFin,
        @WebParam(name = "nombreOrganizador", partName = "nombreOrganizador")
        String nombreOrganizador,
        @WebParam(name = "ciudad", partName = "ciudad")
        String ciudad,
        @WebParam(name = "pais", partName = "pais")
        String pais,
        @WebParam(name = "nombreEvento", partName = "nombreEvento")
        String nombreEvento,
        @WebParam(name = "imagen", partName = "imagen")
        String imagen,
        @WebParam(name = "videoUrl", partName = "videoUrl")
        String videoUrl)
        throws NombreEdicionException_Exception
    ;

    /**
     * 
     * @param nombreEvento
     * @return
     *     returns publicar.EdicionDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarEdicionesDeEventoDTORequest", output = "http://publicar/WebServices/listarEdicionesDeEventoDTOResponse")
    public EdicionDTOArray listarEdicionesDeEventoDTO(
        @WebParam(name = "nombreEvento", partName = "nombreEvento")
        String nombreEvento);

    /**
     * 
     * @param nombre
     * @return
     *     returns publicar.EdicionDTO
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/buscarEdicionDTORequest", output = "http://publicar/WebServices/buscarEdicionDTOResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/buscarEdicionDTO/Fault/BusinessException")
    })
    public EdicionDTO buscarEdicionDTO(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param aporteEconomico
     * @param cantidadRegistros
     * @param codigoPatrocinio
     * @param nivelPatrocinio
     * @param nombreEdicion
     * @param nombreEvento
     * @param nombreInstitucion
     * @param nombreTipoRegistro
     * @throws CostoRegistrosExcedidoException_Exception
     * @throws PatrocinioDuplicadoException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/altaPatrocinioRequest", output = "http://publicar/WebServices/altaPatrocinioResponse", fault = {
        @FaultAction(className = CostoRegistrosExcedidoException_Exception.class, value = "http://publicar/WebServices/altaPatrocinio/Fault/CostoRegistrosExcedidoException"),
        @FaultAction(className = PatrocinioDuplicadoException_Exception.class, value = "http://publicar/WebServices/altaPatrocinio/Fault/PatrocinioDuplicadoException")
    })
    public void altaPatrocinio(
        @WebParam(name = "nombreEvento", partName = "nombreEvento")
        String nombreEvento,
        @WebParam(name = "nombreEdicion", partName = "nombreEdicion")
        String nombreEdicion,
        @WebParam(name = "nombreTipoRegistro", partName = "nombreTipoRegistro")
        String nombreTipoRegistro,
        @WebParam(name = "nombreInstitucion", partName = "nombreInstitucion")
        String nombreInstitucion,
        @WebParam(name = "nivelPatrocinio", partName = "nivelPatrocinio")
        String nivelPatrocinio,
        @WebParam(name = "aporteEconomico", partName = "aporteEconomico")
        String aporteEconomico,
        @WebParam(name = "cantidadRegistros", partName = "cantidadRegistros")
        int cantidadRegistros,
        @WebParam(name = "codigoPatrocinio", partName = "codigoPatrocinio")
        String codigoPatrocinio)
        throws CostoRegistrosExcedidoException_Exception, PatrocinioDuplicadoException_Exception
    ;

    /**
     * 
     * @param nombre
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/existeInstitucionRequest", output = "http://publicar/WebServices/existeInstitucionResponse")
    public boolean existeInstitucion(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre);

    /**
     * 
     * @param descripcion
     * @param nombre
     * @param sitioWeb
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/altaInstitucionRequest", output = "http://publicar/WebServices/altaInstitucionResponse")
    public boolean altaInstitucion(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion,
        @WebParam(name = "sitioWeb", partName = "sitioWeb")
        String sitioWeb);

    /**
     * 
     * @param nickname
     * @return
     *     returns publicar.RegistroDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/getRegistrosPorAsistentesRequest", output = "http://publicar/WebServices/getRegistrosPorAsistentesResponse")
    public RegistroDTOArray getRegistrosPorAsistentes(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname);

    /**
     * 
     * @return
     *     returns publicar.AsistenteDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarAsistentesDTORequest", output = "http://publicar/WebServices/listarAsistentesDTOResponse")
    public AsistenteDTOArray listarAsistentesDTO();

    /**
     * 
     * @param nombreEdicion
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/obtenerTiposDeRegistroDeEdicionRequest", output = "http://publicar/WebServices/obtenerTiposDeRegistroDeEdicionResponse")
    public StringArray obtenerTiposDeRegistroDeEdicion(
        @WebParam(name = "nombreEdicion", partName = "nombreEdicion")
        String nombreEdicion);

    /**
     * 
     * @param nicknameAsistente
     * @param nombreEdicion
     * @param nombreTipoRegistro
     * @throws CupoLlenoException_Exception
     * @throws RegistroDuplicadoException_Exception
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/registrarAsistenteRequest", output = "http://publicar/WebServices/registrarAsistenteResponse", fault = {
        @FaultAction(className = CupoLlenoException_Exception.class, value = "http://publicar/WebServices/registrarAsistente/Fault/CupoLlenoException"),
        @FaultAction(className = RegistroDuplicadoException_Exception.class, value = "http://publicar/WebServices/registrarAsistente/Fault/RegistroDuplicadoException")
    })
    public void registrarAsistente(
        @WebParam(name = "nicknameAsistente", partName = "nicknameAsistente")
        String nicknameAsistente,
        @WebParam(name = "nombreEdicion", partName = "nombreEdicion")
        String nombreEdicion,
        @WebParam(name = "nombreTipoRegistro", partName = "nombreTipoRegistro")
        String nombreTipoRegistro)
        throws CupoLlenoException_Exception, RegistroDuplicadoException_Exception
    ;

    /**
     * 
     * @param cantidad
     * @return
     *     returns net.java.dev.jaxb.array.StringArrayArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/obtenerEventosMasVisitadosRequest", output = "http://publicar/WebServices/obtenerEventosMasVisitadosResponse")
    public StringArrayArray obtenerEventosMasVisitados(
        @WebParam(name = "cantidad", partName = "cantidad")
        int cantidad);

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarPatrociniosRequest", output = "http://publicar/WebServices/listarPatrociniosResponse")
    public StringArray listarPatrocinios();

    /**
     * 
     * @param codigoPatrocinio
     * @return
     *     returns publicar.PatrocinioDTO
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/buscarPatrocinioDTORequest", output = "http://publicar/WebServices/buscarPatrocinioDTOResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://publicar/WebServices/buscarPatrocinioDTO/Fault/BusinessException")
    })
    public PatrocinioDTO buscarPatrocinioDTO(
        @WebParam(name = "codigoPatrocinio", partName = "codigoPatrocinio")
        String codigoPatrocinio)
        throws BusinessException_Exception
    ;

}
